# Run during the 'gulp build' command
# Overrides these options in _config.yml
title: Aim4Strength Fitness
description: Personalized Fitness Training
url: https://aim4strength-comments.netlify.com

author:
  email: julie@aim4strength.com
  name: Julie Smith
  picture: >-
    https://res.cloudinary.com/aim4strength/image/upload/v1514757369/julie-smith.png
  url: 'https://aim4strength.com/meet-julie/'
  bio: >-
    Hello, my friends! My name is Julie Smith. If you would have told me that I was going to become a personal trainer, I would have told you that you were crazy! I have been heavy all of my life—I do mean since age 5. [This is my story.](https://aim4strength.com/meet-julie/)

default-right-aside-cta: 'Thank you for reading. If you have found this article helpful please comment, share, subscribe. It means so much! :heart:'
