# Run during the 'gulp build' command
# Overrides these options in _config.yml
title: Aim4Strength Fitness
description: Personalized Fitness Training
url: https://aim4strength-comments.netlify.com

author:
  email: julie@aim4strength.com
  name: Julie Smith
  picture: >-
    https://res.cloudinary.com/aim4strength/image/upload/v1514757369/julie-smith.png
  url: 'https://aim4strength.com/meet-julie/'
  bio: >-
    Hello, my friends! My name is Julie Smith. If you would have told me that I was going to become a personal trainer, I would have told you that you were crazy! I have been heavy all of my life—I do mean since age 5. [This is my story.](https://aim4strength.com/meet-julie/)

default-right-aside-cta: 'Thank you for reading. If you have found this article helpful please comment, share, subscribe. It means so much! :heart:'

privacy-policy-short: 'Privacy: Policy: Your email address will not be published or shared.'

comment-policy: 'Comment Policy: We do our best to respond particularly on new articles, but don’t have the ability to respond to every comment. Insults and disrespectful comments are not accepted. Please do not include links not pertinent to the discussion. Thank you.'

affiliates:
  name: Tiger Fitness
    logo: https://tigerfitness-tigerfitness.netdna-ssl.com/pub/static/version1514955845/frontend/Tigerfitness/tiger/en_US/images/logo.png
    url: http://www.tigerfitness.com/?a_aid=5a25916a3cb47
    description: TigerFitness.com for the best priced nutritional supplements and customer service in the industry.
