# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Aim4Strength Fitness
description: Personalized Fitness Training
url: http://localhost:3000
# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: .tmp/src
destination: .tmp/dist
include: [_redirects, google0f065b426978137f.html,BingSiteAuth.xml]
exclude: ['assets']

algolia:
  application_id: 'ORE1OKWCML'
  index_name:     'aim4strength_index'
  search_only_api_key: '2960adbde57968159b658bea3b728be8'

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
# NOTE: Don't use @ in front of your Twitter username
author:
  name: Julie Smith
  email: julie@aim4strength.com
  picture: https://res.cloudinary.com/aim4strength/image/upload/v1514757369/julie-smith.png
  url: https://aim4strength.com/meet-julie/

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: false
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
# limit_posts: 10

# Permalink structure and pagination options
permalink: blog/:year/:month/:title/

# Markdown library and options
markdown: kramdown
highlighter: rouge

# Extending Jekyll
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate-v2
  - jekyll-algolia

# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page

#collections_dir: my_collections

collections:
  services:
    output: true
    permalink: /:collection/:title/
  testimonials:
    output: false

defaults:
  -
    scope:
      path: ""
      type: services
    values:
      layout: default
      right-aside-bottom: false
  -
    scope:
      path: ""      # empty string for all files
      type: pages   # limit to posts
    values:
      layout: default
      right-aside-bottom: false
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is-post: true
      cta: "Thank you for reading."
  -
    scope:
      path: ""      # empty string for all files
      type: categories   # limit to posts
    values:
      category: :category

############################################################
# Site configuration for the Auto-Pages feature
# The values here represent the defaults if nothing is set
autopages:

  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: true
  collections:
    enabled: false
  tags:
    enabled: false
  categories:
    layouts:
      - 'autopage.html'
    title: 'Posts in category :cat'
    permalink: '/blog/category/:cat'
