author:
  email: julie@aim4strength.com
  name: Julie Smith
  picture: >-
    https://res.cloudinary.com/aim4strength/image/upload/v1514757369/julie-smith.png
  url: 'https://aim4strength.com/meet-julie/'
